[package]
name = "chic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.9.1"
lazy_static = "1.5.0"

[build-dependencies]
slint-build = "1.9.1"
